name: Deploy

on: [ push, workflow_dispatch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -f ./PacketWrapper/pom.xml deploy -s ./.github-actions/maven/settings.xml

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: plugin
          path: PacketWrapper/target/PacketWrapper.jar
